# Generated by Django 5.1.7 on 2025-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyceeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('lycee_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('profile_type', models.CharField(max_length=100)),
                ('usage_purpose', models.CharField(max_length=100)),
                ('articles_visited', models.TextField()),
                ('page_views', models.IntegerField()),
                ('session_duration', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
